[package]
name = "xfm"
version.workspace = true
edition.workspace = true

[[bin]]
name = "xfm"
path = "src/main.rs"

[dependencies]
xiee-common = { path = "../xiee-common" }
xiee-gui = { path = "../xiee-gui" }
egui.workspace = true
eframe.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
